In [9]:
import numpy as np
from more_itertools import chunked

a = np.array([[1,2,3,4,5], [6,7,8,9,10], [11, 6,7,8,9]])

print(a + (np.array([[1], [2], [3]])))

[[ 2  3  4  5  6]
 [ 8  9 10 11 12]
 [14  9 10 11 12]]
